### ISSUE TITLE
Terminal currently throwing webpack connect error

### ISSUE THREAD

**Issue by chopfitzroy** [command-line-bootcamp/command_line_bootcamp#14]
Receiving this error:

![onpaste 20160910-230207](https://cloud.githubusercontent.com/assets/2978850/18410019/a2c2bff8-77aa-11e6-81a3-1ee114843de9.png)

**Comment by blahah** [comment]
thanks for the heads up! now fixed :)

**Comment by chopfitzroy** [comment]
Hey @blahah is there anything special you are doing with your environment after following your instructions when I run:

``` bash
docker-browser-server command_line_bootcamp
```

And then visit [localhost:8080](http://localhost:8080/) I receive the following output in my terminal:

```
Server is listening on port 8080
Spawning new container (wdhvzkwsqsbrzfr)
Killing container (wdhvzkwsqsbrzfr)
```

Any ideas?

**Comment by chopfitzroy** [comment]
Side not the repo is hard set to `46.101.11.144:8080` as well so anyone building locally is connecting to your server.

Cheers.

**Comment by blahah** [comment]
The interface exposed on port 8080 is only the docker-browser-server HTTP API. You need to point the frontend at it to get a meaningful interface - replace the `46.101.11.144` with `localhost`, then serve up the index.html locally (e.g. with `python -m SimpleHTTPServer` in the git repo directory) and it should connect.

**Comment by chopfitzroy** [comment]
Hey,

Yep sorry I get that :) more having an issue with the container being killed as soon as it is started.

Would you mind running `docker -v` and let me know what version you are running, I have a sneaking suspicion `docker-browser-server` is not even managing to start the container.

Cheers,
Otis.

**Comment by blahah** [comment]
```
# docker -v
Docker version 1.9.1, build a34a1d5
```

**Comment by chopfitzroy** [comment]
Cheers.
