### ISSUE TITLE
Error message now appearing in terminal pane

### ISSUE THREAD

**Issue by mfernandes61** [command-line-bootcamp/command_line_bootcamp#15]
Hi this was working fine both on your public page and on my local installation up until last week.
However now the top right pane has this in it:
WebSocket connection error. Open DevTools for more information.  
and you can't type in commands.
Has something changed recently?

**Comment by blahah** [comment]
This was probably an issue with the server being unreachable or overloaded. It has been working pretty solidly for all of 2017 I think, so I'm closing this. Please feel free to reopen it it happens again.
