### ISSUE TITLE
websocket connection error

### ISSUE THREAD

**Issue by Vicbuz** [command-line-bootcamp/command_line_bootcamp#21]
Hello,

I'm trying to use this command-line bootcamp, but the docker container will not load. It says "WebSocket connection error. Open DevTools for more information."

Am I running it wrong? Do I need to use a different browser? I'm currently in chrome.

**Comment by blahah** [comment]
Sorry about that, something on the server had crashed. I've set that service to auto-restart itself, so this shouldn't happen again, and it should work now :)
