### ISSUE TITLE
WebSocket connection error

### ISSUE THREAD

**Issue by BenLangmead** [command-line-bootcamp/command_line_bootcamp#22]
This morning I'm getting "WebSocket connection error.  Open DevTools for more information."  When I try to use the command-line bootcamp.  Is this temporary?  I would like to use it for a class today if possible.

**Comment by blahah** [comment]
Ah, sorry, it seems a lot more people are using this recently and sometimes the instance runs out of memory. Rebooting now.

Longer term I need to look into a solution where docker can prevent itself using too much memory and provide an informative message.

**Comment by blahah** [comment]
Confirmed it's now back up and running. Thanks for your patience and sorry if it wasn't available for the class.

**Comment by BenLangmead** [comment]
Thank you!  No problem -- it's enough time for students to prep for next lecture tomorrow.  Many thanks for this great resource.  I recommend it to many people.

**Comment by BenLangmead** [comment]
It's back again -- "WebSocket connection error..."

**Comment by blahah** [comment]
Sorry, this ended up being a maze of docker issues. I think I've ironed it out for now. I will soon add a way for anyone to use their own digitalocean droplet for the docker server, which will allow you to have a specific server for your class.
