### ISSUE TITLE
"man" command doesn't show much (referenced in page 12)

### ISSUE THREAD

**Issue by lelutin** [command-line-bootcamp/command_line_bootcamp#29]
Hi there!

I've just reached page 12 and tried out the commands and I can see that the examples don't show much information:

~~~
learner@:~$ man ls                                                                                  
No manual entry for ls                                                                              
See 'man 7 undocumented' for help when manual pages are not available.                              
learner@:~$ man cd                                                                                  
No manual entry for cd                                                                              
learner@:~$ man man                                                                                 
No manual entry for man                                                                             
See 'man 7 undocumented' for help when manual pages are not available.                              
learner@:~$ man find                                                                                
No manual entry for find                                                                            
See 'man 7 undocumented' for help when manual pages are not available.                              
learner@:~$ man 7 undocumented                                                                      
No manual entry for undocumented in section 7
~~~

also from these examples, "cd" and "ls" are usually builtin commands in bash, or other shells and so on linux you probably wouldn't get too much information from "man ls" or "man cd". maybe it would be interesting to show one more command that does usually have a man page before reaching examples for the "man" command?

**Comment by lelutin** [comment]
oh .. sorry for the lack of context. the message above is in the context that I was using the website linked in the project's description, on domain rik.smith-unna.com (and not a self-hosted version of the code) -- so the code version would be whatever is deployed currently there.

**Comment by lelutin** [comment]
oh .. sorry for the lack of context. the message above is in the context that I was using the website linked in the project's description, on domain rik.smith-unna.com (and not a self-hosted version of the code) -- so the code version would be whatever is deployed currently there.

**Comment by lelutin** [comment]
oops, page number is actually 11. I wasn't paying enough attention and I had switched to the next one already..

**Comment by alexmorley** [comment]
Should be fixed :slightly_smiling_face:
