### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by jxchong** [command-line-bootcamp/command_line_bootcamp#32]
Getting error:  WebSocket connection error. Open DevTools for more information.

**Comment by blahah** [comment]
@alexmorley can you restart the server?

**Comment by alexmorley** [comment]
Fixed. Not got time to work out what was busted yet but gonna open another issue to make it slightly more resilient.

**Comment by mbrazas** [comment]
@alexmorley 
This seems to be crashed again. We have given your UNIX tutorial as pre-work for an upcoming bioinformatics class and students are getting the "WebSocket connection error. Open DevTools for more information"
