### ISSUE TITLE
"WebSocket connection error. Open DevTools for more information."

### ISSUE THREAD

**Issue by franzosa** [command-line-bootcamp/command_line_bootcamp#34]
Seeing the error "WebSocket connection error. Open DevTools for more information." when I first navigate to the site. Was hoping to use this great resource once again for an "intro to the command line" lecture on Thursday, but this error is a first for me.

**Comment by blahah** [comment]
This is a recurring problem that we are yet to diagnose - thanks for your patience!

see also #32

**Comment by blahah** [comment]
@alexmorley can you try restarting? And I will take a look this weekend at a more sustainable solution

**Comment by CIWa** [comment]
Unfortunately, I just faced the same error. A restart did not help in my case.

**Comment by alexmorley** [comment]
Restarted. Closing this one as we can track in #33
