### ISSUE TITLE
WebSocket connection error

### ISSUE THREAD

**Issue by nikfm** [command-line-bootcamp/command_line_bootcamp#35]
From this week (07 Jan 2019) I've received a websocket error on multiple browsers.

"WebSocket connection error. Open DevTools for more information."

I see this issue has come up before so hopefully it's an easy fix. Love using this tutorial for teaching command line basics!

**Comment by eth030** [comment]
i am getting the same issue, can we get a fix here?

**Comment by eth030** [comment]
terminal-bundle.js:11966 WebSocket connection to 'ws://1x.x.x.:8080/x9bwcoxmusn' failed: Error in connection establishment: net::ERR_PROXY_AUTH_REQUESTED_WITH_NO_CONNECTION
ws @ terminal-bundle.js:11966

**Comment by blahah** [comment]
Hi both, thanks for reporting this. The issue is that the server will have run out of resources. We'll try to get it back up asap.

cc @alexmorley could you reboot?

**Comment by nnrahm** [comment]
Hello,
Any updates on this? I am needing it for a class and haven't been able to access it properly for days.

**Comment by blahah** [comment]
Sorry, we currently don't have funding to run the servers. We do have several people who have offered to provide cloud instances, and we are actively looking for sponsors.

There is always the option for anyone to fork this repo and host the backend themselves. You just follow the instructions in the README to set up the server part, then modify this line (https://github.com/blahah/command_line_bootcamp/blob/master/index.js#L15) to the new IP address and host the repo on Github pages.

**Comment by alexmorley** [comment]
The site is up again for now...
