### ISSUE TITLE
Command Line Bootcamp Issue

### ISSUE THREAD

**Issue by lucklepper** [command-line-bootcamp/command_line_bootcamp#38]
For page 27:
http://rik.smith-unna.com/command_line_bootcamp/?id=jfc92zj308r

The link is obsolete; i've tried replacing with https://github.com/blahah/command_line_bootcamp/blob/master/testfiles/grades.txt 

But this does not appear to return the file content.

**Comment by alexmorley** [comment]
I think this is fixed. FYI you have to click on the "raw" button on a textfile on github for it to give you the right link to copy and paste (otherwise you are downloading the whole page not just the text).
