### ISSUE TITLE
Connection timeout.

### ISSUE THREAD

**Issue by Aaranaw** [command-line-bootcamp/command_line_bootcamp#39]
Hi, I have worked my way through the setup instructions however I am unable to connect to the interface, chrome reports 

> This site can’t be reached IPADDRESS:8080 took too long to respond.

However `docker-browser-server command_line_bootcamp -p 8080` is running `Server is listening on port 8080`

I am unsure if this is an issue with the server I am running it on (centos7), command line bootcamp, or docker-browser-server.

**Comment by atm44** [comment]
Did you access to 127.0.0.1:8080?

**Comment by alexmorley** [comment]
Closing as this is old now. Live site is up again too at a new url (https://alexmorley.me/command_line_bootcamp/?secure=T): see #40
