### ISSUE TITLE
WebSocket connection error on public/live site

### ISSUE THREAD

**Issue by obigriffith** [command-line-bootcamp/command_line_bootcamp#40]
FYI. The live site at "http://rik.smith-unna.com/command_line_bootcamp" has been non-functional for several weeks with "WebSocket connection error. Open DevTools for more information".

**Comment by abalter** [comment]
Yup! This is a great resource! Could we get this running again?

**Comment by jxchong** [comment]
Sadly website is still down. :(

**Comment by atm44** [comment]
+1

**Comment by alexmorley** [comment]
Sorry for this folks. I can try and sort it out this weekend. If someone reads this past 5th May and I haven't done anything then please feel free to reach out / ping again.

**Comment by StuntsPT** [comment]
Ping, as requested. =-)

This is really useful for beginner students.

**Comment by alexmorley** [comment]
DONE! I don't know what Rik has done to his personal site but it's broken the frontend there too so use this link for now: http://alexmorley.me/command_line_bootcamp

I'll see how much a proper domain will be and put it there instead.

**Comment by alexmorley** [comment]
Hmm actually need to move everything over to ssl to stop browser giving security errors. Still WIP.

**Comment by StuntsPT** [comment]
Thank you so much for keeping this alive. Your effort is appreciated. =-)

**Comment by alexmorley** [comment]
https://alexmorley.me/command_line_bootcamp/?secure=T   :tada:  <--    give that one a try and report back. I'll get rid of it needing that `?secure=T` later.

**Comment by alexmorley** [comment]
Works for me on firefox and chrome though so should be all good.

**Comment by StuntsPT** [comment]
Confirming the "Worksforme" status on firefox. =-)

Thank you!!

**Comment by blahah** [comment]
> DONE! I don't know what Rik has done to his personal site but it's broken the frontend there

Someone stole my family domain while I was incapacitated due to illness. Boo!

Sorry for the trouble folks. So much love for @alexmorley keeping this running despite the many barriers. New domain is https://cli-boot.camp/
