### ISSUE TITLE
Remove query parameter requirement when hosted over ssl

### ISSUE THREAD

**Issue by alexmorley** [command-line-bootcamp/command_line_bootcamp#43]
At the moment we have to use a query param `secure=T` to make sure that the websocket uses the wss protocol (ws with ssl). It just needs a quick patch of adventure-time but to allow setting this some other way: `https://github.com/maxogden/adventure-time/blob/9d814c6190bc6434c2278b5d3772b8470b6d9321/terminal.js#L14`

or we can just add the param ourselves in before that call is made (even easier).

**Comment by blahah** [comment]
Let's fork adventure time to this org and use that fork as a dependency instead?

We can PR it upstream and merge later.

**Comment by blahah** [comment]
We always want it to be secure right? So we can just set it on?

**Comment by blahah** [comment]
https://github.com/command-line-bootcamp/adventure-time/commit/49514d44e009418e2a21d11bc8ee9ba1a047077d

**Comment by blahah** [comment]
https://github.com/command-line-bootcamp/command_line_bootcamp/commit/3b60f8a775bf16fd394192b489689111295b0065

**Comment by blahah** [comment]
Just needs a pull and restart, should be fixed :purple_heart:

**Comment by alexmorley** [comment]
Nice. Will do that tommorrow.
