### ISSUE TITLE
File system exposure does not work

### ISSUE THREAD

**Issue by atm44** [command-line-bootcamp/command_line_bootcamp#44]
Hello, I think there is something wrong with the docker that does not respond to the request for "files" and therefore the file explorer does not work.

Bloqueado al cargar contenido de visualización mixto "http://command-line-bootcamp-backend.alexmorley.me:8443/files/pv9ccj8pvlb/"

Edit: Also, and probably related, when you use the console for the first time, it shows you the following line from the dockerfile:
`expose-fs >> .fs.out 2>> .fs.err       `

**Comment by alexmorley** [comment]
Hey @atm44 can you give this another test for me? After a couple of fixes it works like 50% of the time for me (the other 50% I get CORs errors).

**Comment by atm44** [comment]
Works excellent! I tried it several times. 
![imagen](https://user-images.githubusercontent.com/8797017/82381809-31d66380-9a01-11ea-807d-910054951683.png)

**Comment by alexmorley** [comment]
🎉  🎉

**Comment by alexmorley** [comment]
Hopefully was just a caching issue 👍
