### ISSUE TITLE
move this repo to an organisation

### ISSUE THREAD

**Issue by blahah** [command-line-bootcamp/command_line_bootcamp#45]
should we move this to an organisation?

This would remove the dependence on me which has been holding back usability when I'm unavailable. And would let you @alexmorley have full powers over the repo, along with anyone else who wants to help.

Thoughts? Suggested name for the org?

**Comment by alexmorley** [comment]
Thoughts: Yes
Suggested Names: 
- Command Line Bootcamp 😅  
- cli-boot.camp (https://www.namecheap.com/domains/registration/results/?domain=cli-boot.camp)
- Adventure Time

**Comment by blahah** [comment]
Conclusions: Agreed
Actions taken:

- [cli-boot.camp](http://cli-boot.camp) are belong to us
- https://github.com/orgs/command-line-bootcamp has entered the timeline
- you're an owner @alexmorley 

Stuff to do:

- [x] migrate repo to the org
- [x] set up the domain
- [x] look at a plant and wonder at the majesty of life

**Comment by blahah** [comment]
Now we live here https://github.com/command-line-bootcamp/command_line_bootcamp

Maybe worth choosing a better name for the repo, to avoid repetition with different spaces. The old one will redirect indefinitely though.

**Comment by blahah** [comment]
And the site is now http://cli-boot.camp - https://cli-boot.camp will work within 24 hours (works for me now in Chrome).

**Comment by alexmorley** [comment]
:tada: All looks like its working fiiiine.

>  - [X] look at a plant and wonder at the majesty of life

My house has been filled with plants during lockdown so its impossible not to do this.

**Comment by blahah** [comment]
Same, it's actually becoming a problem. But a wonderful problem to have.
