### ISSUE TITLE
WebSocket connection error?

### ISSUE THREAD

**Issue by rikander** [command-line-bootcamp/command_line_bootcamp#47]
Hi folks,

I tried testing this again today (I've used it as a teaching tool during the first week of my Genomics and Bioinformatics class for the past few years, and it is GREAT!) and I noticed that the little terminal window in the browser says "WebSocket connection error. Open DevTools for more information." The interface doesn't respond when I type simple commands. Is this a bug that was introduced recently, or is this a problem on my end? (Tried this in Chrome, Firefox, and Safari. No dice.)

Thanks so much for putting this together! It's perfect for my students!
Rika

**Comment by alexmorley** [comment]
Hey. I'll have a look at the weekend. Thanks for reporting 😃. If I don't respond by Tuesday please feel free to nudge again.

**Comment by rikander** [comment]
Hi again! Thanks for your response earlier! Just checking in-- it looks like the same error is still up. Thanks!

**Comment by danieltaylor** [comment]
Looks like this is still an issue.  I would love to share this page with my classmates once it's up and running again.

**Comment by alexmorley** [comment]
Thanks for reporting @rikander and @danieltaylor. Sorry I couldn't get to it earlier but its fixed now!

**Comment by alexmorley** [comment]
Pls re-open if not ✨
