### ISSUE TITLE
Question: cpu and memory requirement for ~30 users

### ISSUE THREAD

**Issue by yeban** [command-line-bootcamp/command_line_bootcamp#48]
Hello. Thanks for creating and maintaining this excellent resource.

I am planning to run a command line bootcamp server on Amazon Web Services for a class of approximately 30 students. I was wondering if know how much CPU and RAM should I allocate for the server. From what I understand, a tiny 1 CPU, 1 GB RAM node should be sufficient for this?

**Comment by alexmorley** [comment]
I reckon you might need a bit more RAM but I'm mostly guessing.

**Comment by yeban** [comment]
Okay, thanks!
