### ISSUE TITLE
Small inconsistencies from a first pass

### ISSUE THREAD

**Issue by jessicalumian** [command-line-bootcamp/command_line_bootcamp#6]
Recently went through the bootcamp up through page 18 and I have a few tidbits. I'd be happy to PR these if you agree about them.

On page 08, prompt should read “learner@:learning_unix” because location is /home/learner/learning_unix

On page 11, "man cd" gives error “No manual entry for cd” (which I didn't know!). Probably should change the example to something else.

On page 17, "mv temp/riches temp/rags" is at end of page 16, so having it again at top of 17 gives the error that temp/riches doesn't exist

On page 18, there is some weird character encoding on first code block around files earth.txt, heaven.txt, and rags. also, might want to say “type y (for yes, vs n for no) press enter” after every rm: …. ? line.  Also, in 17, told to make temp3 and mv into temp. so, rmdir temp2/temp3 doesn’t work because temp2/temp3 doesn’t exist (both temp2 and temp3 are in temp)

**Comment by blahah** [comment]
Thanks so much for this :)

All those are good catches - I'd be very happy to have a PR.

There _should_ be a man entry for `cd` - the Docker image comes without any manpages and I installed some basic set by `apt-get install man` in the `Dockerfile`. There must be another package with more in - will investigate.

**Comment by blahah** [comment]
Resolved in #7
