### ISSUE TITLE
Investigate FireFox/umaxtrix issues

### ISSUE THREAD

**Issue by blahah** [command-line-bootcamp/command_line_bootcamp#8]
See https://twitter.com/oObsi/status/672098502655242245

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr"><a href="https://twitter.com/blahah404">@blahah404</a> ff42 seems to dislike cleartext websockets?also no dice with https, the JS doesnt dial wss (mix-content) <a href="https://t.co/jeJn7eGHEQ">pic.twitter.com/jeJn7eGHEQ</a></p>&mdash; Henry B. (@oObsi) <a href="https://twitter.com/oObsi/status/672098502655242245">December 2, 2015</a></blockquote>

**Comment by lelutin** [comment]
this seems to still be an issue now with firefox 57

**Comment by lelutin** [comment]
for what it's worth, https://try-dat.com/ seems to have reused some of the code from here and their terminal via websocket is working. so you might be able to find the fix already implemented over there.

I can't find the code repository for what's on try-dat.com though. maybe you can try contacting them by email (there's a contact address on dat's website dat-data.com)

**Comment by blahah** [comment]
Hey, I know the dat team - this project was actually created using their code rather than the other way round. I just tested the site in FF 57 on macOS 10.13 and it works for me. Please could you provide some more detail about your setup? Particularly operating system and exact FF version.

**Comment by lelutin** [comment]
I'm using firefox 57.0 on debian sid(unstable). I also use ublock origin and umatrix

**Comment by blahah** [comment]
@lelutin the problem may very well be umatrix. Would you be able to try the site and take a screenshot of what umatrix blocks?

**Comment by lelutin** [comment]
Here's the screenshot:

![command_line_bootcamp_ff_websockets](https://user-images.githubusercontent.com/108728/36051266-82487dcc-0db7-11e8-8069-d2b8a08de345.png)

The choices of what's blocked is just the default ones.

**Comment by alexmorley** [comment]
I think umatrix is stopping you from connecting to the backend via the websocket. I think you'll need to allow the XMLHttpRequest (XHR) to the unamed ip. You can verify that is indeed the backed currently used by the bootcamp by checking out [the source](https://github.com/blahah/command_line_bootcamp/blob/gh-pages/index.js).

**Comment by lelutin** [comment]
@alexmorley hey that seems to do it! thanks for the information.

I am usually wary of code being loaded from unnamed IPs. If the websocket could be hosted under the same domain it would make this less concerning... however, I haven't looked much at the code and I don,t know much about how things work so maybe this is not easily feasible.

**Comment by alexmorley** [comment]
At the moment the static part is served by github and the Dockers are elsewhere so I'm going to close for now but perhaps we can host all in one place in the future.
